# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a corrupted csv file.

## Objectives
You will be able to:

- Use pandas to import data from a CSV and and an Excel spreadsheet  

##  Loading Files with Summary or Meta Data

Load either of the files `'Zipcode_Demos.csv'` or `'Zipcode_Demos.xlsx'`. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled `'Data'`.

In [1]:
# Import pandas using the standard alias
import pandas as pd

In [2]:
# Import the file and print the first 5 rows
df = pd.read_csv('Zipcode_Demos.csv')
df.head()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,1,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,JURISDICTION NAME,10005.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,COUNT PARTICIPANTS,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,COUNT FEMALE,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PERCENT FEMALE,0.404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Print the last 5 rows of df
df.tail()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [4]:
# What is going on with this data set? Anything unusual?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 47 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   0                   57 non-null     int64
 1   Average Statistics  56 non-null     object
 2   Unnamed: 2          57 non-null     object
 3   Unnamed: 3          11 non-null     object
 4   Unnamed: 4          11 non-null     object
 5   Unnamed: 5          11 non-null     object
 6   Unnamed: 6          11 non-null     object
 7   Unnamed: 7          11 non-null     object
 8   Unnamed: 8          11 non-null     object
 9   Unnamed: 9          11 non-null     object
 10  Unnamed: 10         11 non-null     object
 11  Unnamed: 11         11 non-null     object
 12  Unnamed: 12         11 non-null     object
 13  Unnamed: 13         11 non-null     object
 14  Unnamed: 14         11 non-null     object
 15  Unnamed: 15         11 non-null     object
 16  Unnamed: 16         11 non-null     object
 17  Unnamed: 17         11 non-null     object
 18  Unnamed: 18         11 non-null     object
 19  Unnamed: 19         11 non-null     object
 20  Unnamed: 20         11 non-null     object
 21  Unnamed: 21         11 non-null     object
 22  Unnamed: 22         11 non-null     object
 23  Unnamed: 23         11 non-null     object
 24  Unnamed: 24         11 non-null     object
 25  Unnamed: 25         11 non-null     object
 26  Unnamed: 26         11 non-null     object
 27  Unnamed: 27         11 non-null     object
 28  Unnamed: 28         11 non-null     object
 29  Unnamed: 29         11 non-null     object
 30  Unnamed: 30         11 non-null     object
 31  Unnamed: 31         11 non-null     object
 32  Unnamed: 32         11 non-null     object
 33  Unnamed: 33         11 non-null     object
 34  Unnamed: 34         11 non-null     object
 35  Unnamed: 35         11 non-null     object
 36  Unnamed: 36         11 non-null     object
 37  Unnamed: 37         11 non-null     object
 38  Unnamed: 38         11 non-null     object
 39  Unnamed: 39         11 non-null     object
 40  Unnamed: 40         11 non-null     object
 41  Unnamed: 41         11 non-null     object
 42  Unnamed: 42         11 non-null     object
 43  Unnamed: 43         11 non-null     object
 44  Unnamed: 44         11 non-null     object
 45  Unnamed: 45         11 non-null     object
 46  Unnamed: 46         11 non-null     object
dtypes: int64(1), object(46)
memory usage: 21.1+ KB

In [4]:
df.shape

(57, 47)

In [5]:
df.describe()

               0
count  57.000000
mean   29.000000
std    16.598193
min     1.000000
25%    15.000000
50%    29.000000
75%    43.000000
max    57.000000

In [6]:
df.isnull()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,False,True,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
5,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
6,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
7,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
8,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
9,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
10,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
11,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
12,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
13,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
14,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
15,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
16,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
17,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
18,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
19,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
20,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
21,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
22,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
23,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
24,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
25,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
26,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
27,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
28,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
29,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
30,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
31,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
32,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
33,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
34,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
35,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
36,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
37,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
38,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
39,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
40,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
41,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
42,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
43,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
44,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
45,False,False,False,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
46,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
53,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
# Clean up the dataset
df.isnull().sum()

0                      0
Average Statistics     1
Unnamed: 2             0
Unnamed: 3            46
Unnamed: 4            46
Unnamed: 5            46
Unnamed: 6            46
Unnamed: 7            46
Unnamed: 8            46
Unnamed: 9            46
Unnamed: 10           46
Unnamed: 11           46
Unnamed: 12           46
Unnamed: 13           46
Unnamed: 14           46
Unnamed: 15           46
Unnamed: 16           46
Unnamed: 17           46
Unnamed: 18           46
Unnamed: 19           46
Unnamed: 20           46
Unnamed: 21           46
Unnamed: 22           46
Unnamed: 23           46
Unnamed: 24           46
Unnamed: 25           46
Unnamed: 26           46
Unnamed: 27           46
Unnamed: 28           46
Unnamed: 29           46
Unnamed: 30           46
Unnamed: 31           46
Unnamed: 32           46
Unnamed: 33           46
Unnamed: 34           46
Unnamed: 35           46
Unnamed: 36           46
Unnamed: 37           46
Unnamed: 38           46
Unnamed: 39           46
Unnamed: 40           46
Unnamed: 41           46
Unnamed: 42           46
Unnamed: 43           46
Unnamed: 44           46
Unnamed: 45           46
Unnamed: 46           46
dtype: int64

In [8]:
df.dropna()

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
46,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
47,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
48,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
49,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
50,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [9]:
for column in df.select_dtypes(include='object'):  # Loop through categorical columns
    df[column].fillna(df[column].mode()[0], inplace=True)

C:\Users\hp\AppData\Local\Temp\ipykernel_4784\1903468508.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mode()[0], inplace=True)

In [10]:
df_Duplicates = df.drop_duplicates
print(df_Duplicates)

<bound method DataFrame.drop_duplicates of      0                   Average Statistics          Unnamed: 2    Unnamed: 3  \
0    1                    JURISDICTION NAME                   0             0
1    2                    JURISDICTION NAME             10005.8             0
2    3                   COUNT PARTICIPANTS                 9.4             0
3    4                         COUNT FEMALE                 4.8             0
4    5                       PERCENT FEMALE               0.404             0
5    6                           COUNT MALE                 4.6             0
6    7                         PERCENT MALE               0.396             0
7    8                 COUNT GENDER UNKNOWN                   0             0
8    9               PERCENT GENDER UNKNOWN                   0             0
9   10                   COUNT GENDER TOTAL                 9.4             0
10  11                 PERCENT GENDER TOTAL                  80             0
11  12               COUNT PACIFIC ISLANDER                   0             0
12  13             PERCENT PACIFIC ISLANDER                   0             0
13  14                COUNT HISPANIC LATINO                   2             0
14  15              PERCENT HISPANIC LATINO               0.105             0
15  16                COUNT AMERICAN INDIAN                   0             0
16  17              PERCENT AMERICAN INDIAN                   0             0
17  18             COUNT ASIAN NON HISPANIC                 3.6             0
18  19           PERCENT ASIAN NON HISPANIC               0.437             0
19  20             COUNT WHITE NON HISPANIC                 0.8             0
20  21           PERCENT WHITE NON HISPANIC               0.036             0
21  22             COUNT BLACK NON HISPANIC                 2.6             0
22  23           PERCENT BLACK NON HISPANIC               0.181             0
23  24                COUNT OTHER ETHNICITY                 0.4             0
24  25              PERCENT OTHER ETHNICITY                0.04             0
25  26              COUNT ETHNICITY UNKNOWN                   0             0
26  27            PERCENT ETHNICITY UNKNOWN                   0             0
27  28                COUNT ETHNICITY TOTAL                 9.4             0
28  29              PERCENT ETHNICITY TOTAL                79.9             0
29  30       COUNT PERMANENT RESIDENT ALIEN                 0.5             0
30  31     PERCENT PERMANENT RESIDENT ALIEN               0.061             0
31  32                     COUNT US CITIZEN                 8.9             0
32  33                   PERCENT US CITIZEN               0.739             0
33  34           COUNT OTHER CITIZEN STATUS                   0             0
34  35         PERCENT OTHER CITIZEN STATUS                   0             0
35  36         COUNT CITIZEN STATUS UNKNOWN                   0             0
36  37       PERCENT CITIZEN STATUS UNKNOWN                   0             0
37  38           COUNT CITIZEN STATUS TOTAL                 9.4             0
38  39         PERCENT CITIZEN STATUS TOTAL                  80             0
39  40     COUNT RECEIVES PUBLIC ASSISTANCE                 2.3             0
40  41   PERCENT RECEIVES PUBLIC ASSISTANCE               0.151             0
41  42    COUNT NRECEIVES PUBLIC ASSISTANCE                 7.1             0
42  43  PERCENT NRECEIVES PUBLIC ASSISTANCE               0.649             0
43  44      COUNT PUBLIC ASSISTANCE UNKNOWN                   0             0
44  45    PERCENT PUBLIC ASSISTANCE UNKNOWN                   0             0
45  46        COUNT PUBLIC ASSISTANCE TOTAL                 9.4             0
46  47                    JURISDICTION NAME  COUNT PARTICIPANTS  COUNT FEMALE
47  48                                10001                  44            22
48  49                                10002                  35            19
49  50                                10003                   1             1
50  51                                10004                   0             0
51  52                                10005                   2             2
52  53                                10006                   6             2
53  54                                10007                   1             0
54  55                                10009                   2             0
55  56                                10010                   0             0
56  57                                10011                   3             2

        Unnamed: 4  Unnamed: 5    Unnamed: 6            Unnamed: 7  \
0                0           0             0                     0
1                0           0             0                     0
2                0           0             0                     0
3                0           0             0                     0
4                0           0             0                     0
5                0           0             0                     0
6                0           0             0                     0
7                0           0             0                     0
8                0           0             0                     0
9                0           0             0                     0
10               0           0             0                     0
11               0           0             0                     0
12               0           0             0                     0
13               0           0             0                     0
14               0           0             0                     0
15               0           0             0                     0
16               0           0             0                     0
17               0           0             0                     0
18               0           0             0                     0
19               0           0             0                     0
20               0           0             0                     0
21               0           0             0                     0
22               0           0             0                     0
23               0           0             0                     0
24               0           0             0                     0
25               0           0             0                     0
26               0           0             0                     0
27               0           0             0                     0
28               0           0             0                     0
29               0           0             0                     0
30               0           0             0                     0
31               0           0             0                     0
32               0           0             0                     0
33               0           0             0                     0
34               0           0             0                     0
35               0           0             0                     0
36               0           0             0                     0
37               0           0             0                     0
38               0           0             0                     0
39               0           0             0                     0
40               0           0             0                     0
41               0           0             0                     0
42               0           0             0                     0
43               0           0             0                     0
44               0           0             0                     0
45               0           0             0                     0
46  PERCENT FEMALE  COUNT MALE  PERCENT MALE  COUNT GENDER UNKNOWN
47             0.5          22           0.5                     0
48            0.54          16          0.46                     0
49               1           0             0                     0
50               0           0             0                     0
51               1           0             0                     0
52            0.33           4          0.67                     0
53               0           1             1                     0
54               0           2             1                     0
55               0           0             0                     0
56            0.67           1          0.33                     0

                Unnamed: 8          Unnamed: 9  ...  \
0                        0                   0  ...
1                        0                   0  ...
2                        0                   0  ...
3                        0                   0  ...
4                        0                   0  ...
5                        0                   0  ...
6                        0                   0  ...
7                        0                   0  ...
8                        0                   0  ...
9                        0                   0  ...
10                       0                   0  ...
11                       0                   0  ...
12                       0                   0  ...
13                       0                   0  ...
14                       0                   0  ...
15                       0                   0  ...
16                       0                   0  ...
17                       0                   0  ...
18                       0                   0  ...
19                       0                   0  ...
20                       0                   0  ...
21                       0                   0  ...
22                       0                   0  ...
23                       0                   0  ...
24                       0                   0  ...
25                       0                   0  ...
26                       0                   0  ...
27                       0                   0  ...
28                       0                   0  ...
29                       0                   0  ...
30                       0                   0  ...
31                       0                   0  ...
32                       0                   0  ...
33                       0                   0  ...
34                       0                   0  ...
35                       0                   0  ...
36                       0                   0  ...
37                       0                   0  ...
38                       0                   0  ...
39                       0                   0  ...
40                       0                   0  ...
41                       0                   0  ...
42                       0                   0  ...
43                       0                   0  ...
44                       0                   0  ...
45                       0                   0  ...
46  PERCENT GENDER UNKNOWN  COUNT GENDER TOTAL  ...
47                       0                  44  ...
48                       0                  35  ...
49                       0                   1  ...
50                       0                   0  ...
51                       0                   2  ...
52                       0                   6  ...
53                       0                   1  ...
54                       0                   2  ...
55                       0                   0  ...
56                       0                   3  ...

                   Unnamed: 37                   Unnamed: 38  \
0                            0                           100
1                            0                           100
2                            0                           100
3                            0                           100
4                            0                           100
5                            0                           100
6                            0                           100
7                            0                           100
8                            0                           100
9                            0                           100
10                           0                           100
11                           0                           100
12                           0                           100
13                           0                           100
14                           0                           100
15                           0                           100
16                           0                           100
17                           0                           100
18                           0                           100
19                           0                           100
20                           0                           100
21                           0                           100
22                           0                           100
23                           0                           100
24                           0                           100
25                           0                           100
26                           0                           100
27                           0                           100
28                           0                           100
29                           0                           100
30                           0                           100
31                           0                           100
32                           0                           100
33                           0                           100
34                           0                           100
35                           0                           100
36                           0                           100
37                           0                           100
38                           0                           100
39                           0                           100
40                           0                           100
41                           0                           100
42                           0                           100
43                           0                           100
44                           0                           100
45                           0                           100
46  COUNT CITIZEN STATUS TOTAL  PERCENT CITIZEN STATUS TOTAL
47                          44                           100
48                          35                           100
49                           1                           100
50                           0                             0
51                           2                           100
52                           6                           100
53                           1                           100
54                           2                           100
55                           0                             0
56                           3                           100

                         Unnamed: 39                         Unnamed: 40  \
0                                  0                                   0
1                                  0                                   0
2                                  0                                   0
3                                  0                                   0
4                                  0                                   0
5                                  0                                   0
6                                  0                                   0
7                                  0                                   0
8                                  0                                   0
9                                  0                                   0
10                                 0                                   0
11                                 0                                   0
12                                 0                                   0
13                                 0                                   0
14                                 0                                   0
15                                 0                                   0
16                                 0                                   0
17                                 0                                   0
18                                 0                                   0
19                                 0                                   0
20                                 0                                   0
21                                 0                                   0
22                                 0                                   0
23                                 0                                   0
24                                 0                                   0
25                                 0                                   0
26                                 0                                   0
27                                 0                                   0
28                                 0                                   0
29                                 0                                   0
30                                 0                                   0
31                                 0                                   0
32                                 0                                   0
33                                 0                                   0
34                                 0                                   0
35                                 0                                   0
36                                 0                                   0
37                                 0                                   0
38                                 0                                   0
39                                 0                                   0
40                                 0                                   0
41                                 0                                   0
42                                 0                                   0
43                                 0                                   0
44                                 0                                   0
45                                 0                                   0
46  COUNT RECEIVES PUBLIC ASSISTANCE  PERCENT RECEIVES PUBLIC ASSISTANCE
47                                20                                0.45
48                                 2                                0.06
49                                 0                                   0
50                                 0                                   0
51                                 0                                   0
52                                 0                                   0
53                                 1                                   1
54                                 0                                   0
55                                 0                                   0
56                                 0                                   0

                          Unnamed: 41                          Unnamed: 42  \
0                                   0                                    1
1                                   0                                    1
2                                   0                                    1
3                                   0                                    1
4                                   0                                    1
5                                   0                                    1
6                                   0                                    1
7                                   0                                    1

In [11]:
df.isnull().sum()

0                     0
Average Statistics    0
Unnamed: 2            0
Unnamed: 3            0
Unnamed: 4            0
Unnamed: 5            0
Unnamed: 6            0
Unnamed: 7            0
Unnamed: 8            0
Unnamed: 9            0
Unnamed: 10           0
Unnamed: 11           0
Unnamed: 12           0
Unnamed: 13           0
Unnamed: 14           0
Unnamed: 15           0
Unnamed: 16           0
Unnamed: 17           0
Unnamed: 18           0
Unnamed: 19           0
Unnamed: 20           0
Unnamed: 21           0
Unnamed: 22           0
Unnamed: 23           0
Unnamed: 24           0
Unnamed: 25           0
Unnamed: 26           0
Unnamed: 27           0
Unnamed: 28           0
Unnamed: 29           0
Unnamed: 30           0
Unnamed: 31           0
Unnamed: 32           0
Unnamed: 33           0
Unnamed: 34           0
Unnamed: 35           0
Unnamed: 36           0
Unnamed: 37           0
Unnamed: 38           0
Unnamed: 39           0
Unnamed: 40           0
Unnamed: 41           0
Unnamed: 42           0
Unnamed: 43           0
Unnamed: 44           0
Unnamed: 45           0
Unnamed: 46           0
dtype: int64

In [12]:
df

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
0,1,JURISDICTION NAME,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
1,2,JURISDICTION NAME,10005.8,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
2,3,COUNT PARTICIPANTS,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
3,4,COUNT FEMALE,4.8,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
4,5,PERCENT FEMALE,0.404,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
5,6,COUNT MALE,4.6,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
6,7,PERCENT MALE,0.396,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
7,8,COUNT GENDER UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
8,9,PERCENT GENDER UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
9,10,COUNT GENDER TOTAL,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
10,11,PERCENT GENDER TOTAL,80,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
11,12,COUNT PACIFIC ISLANDER,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
12,13,PERCENT PACIFIC ISLANDER,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
13,14,COUNT HISPANIC LATINO,2,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
14,15,PERCENT HISPANIC LATINO,0.105,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
15,16,COUNT AMERICAN INDIAN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
16,17,PERCENT AMERICAN INDIAN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
17,18,COUNT ASIAN NON HISPANIC,3.6,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
18,19,PERCENT ASIAN NON HISPANIC,0.437,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
19,20,COUNT WHITE NON HISPANIC,0.8,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
20,21,PERCENT WHITE NON HISPANIC,0.036,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
21,22,COUNT BLACK NON HISPANIC,2.6,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
22,23,PERCENT BLACK NON HISPANIC,0.181,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
23,24,COUNT OTHER ETHNICITY,0.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
24,25,PERCENT OTHER ETHNICITY,0.04,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
25,26,COUNT ETHNICITY UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
26,27,PERCENT ETHNICITY UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
27,28,COUNT ETHNICITY TOTAL,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
28,29,PERCENT ETHNICITY TOTAL,79.9,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
29,30,COUNT PERMANENT RESIDENT ALIEN,0.5,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
30,31,PERCENT PERMANENT RESIDENT ALIEN,0.061,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
31,32,COUNT US CITIZEN,8.9,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
32,33,PERCENT US CITIZEN,0.739,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
33,34,COUNT OTHER CITIZEN STATUS,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
34,35,PERCENT OTHER CITIZEN STATUS,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
35,36,COUNT CITIZEN STATUS UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
36,37,PERCENT CITIZEN STATUS UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
37,38,COUNT CITIZEN STATUS TOTAL,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
38,39,PERCENT CITIZEN STATUS TOTAL,80,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
39,40,COUNT RECEIVES PUBLIC ASSISTANCE,2.3,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
40,41,PERCENT RECEIVES PUBLIC ASSISTANCE,0.151,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
41,42,COUNT NRECEIVES PUBLIC ASSISTANCE,7.1,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
42,43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
43,44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
44,45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
45,46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
46,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
47,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
48,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
49,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
50,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [21]:
df.columns = [
    f"Column_{i}" if "Unnamed" in str(col) else col 
    for i, col in enumerate(df.columns)
]
df.columns

Index(['0', 'Average Statistics', 'Column_2', 'Column_3', 'Column_4',
       'Column_5', 'Column_6', 'Column_7', 'Column_8', 'Column_9', 'Column_10',
       'Column_11', 'Column_12', 'Column_13', 'Column_14', 'Column_15',
       'Column_16', 'Column_17', 'Column_18', 'Column_19', 'Column_20',
       'Column_21', 'Column_22', 'Column_23', 'Column_24', 'Column_25',
       'Column_26', 'Column_27', 'Column_28', 'Column_29', 'Column_30',
       'Column_31', 'Column_32', 'Column_33', 'Column_34', 'Column_35',
       'Column_36', 'Column_37', 'Column_38', 'Column_39', 'Column_40',
       'Column_41', 'Column_42', 'Column_43', 'Column_44', 'Column_45',
       'Column_46'],
      dtype='object')

In [22]:
df

,0,Average Statistics,Column_2,Column_3,Column_4,Column_5,Column_6,Column_7,Column_8,Column_9,...,Column_37,Column_38,Column_39,Column_40,Column_41,Column_42,Column_43,Column_44,Column_45,Column_46
0,1,JURISDICTION NAME,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
1,2,JURISDICTION NAME,10005.8,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
2,3,COUNT PARTICIPANTS,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
3,4,COUNT FEMALE,4.8,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
4,5,PERCENT FEMALE,0.404,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
5,6,COUNT MALE,4.6,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
6,7,PERCENT MALE,0.396,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
7,8,COUNT GENDER UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
8,9,PERCENT GENDER UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
9,10,COUNT GENDER TOTAL,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
10,11,PERCENT GENDER TOTAL,80,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
11,12,COUNT PACIFIC ISLANDER,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
12,13,PERCENT PACIFIC ISLANDER,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
13,14,COUNT HISPANIC LATINO,2,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
14,15,PERCENT HISPANIC LATINO,0.105,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
15,16,COUNT AMERICAN INDIAN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
16,17,PERCENT AMERICAN INDIAN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
17,18,COUNT ASIAN NON HISPANIC,3.6,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
18,19,PERCENT ASIAN NON HISPANIC,0.437,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
19,20,COUNT WHITE NON HISPANIC,0.8,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
20,21,PERCENT WHITE NON HISPANIC,0.036,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
21,22,COUNT BLACK NON HISPANIC,2.6,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
22,23,PERCENT BLACK NON HISPANIC,0.181,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
23,24,COUNT OTHER ETHNICITY,0.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
24,25,PERCENT OTHER ETHNICITY,0.04,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
25,26,COUNT ETHNICITY UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
26,27,PERCENT ETHNICITY UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
27,28,COUNT ETHNICITY TOTAL,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
28,29,PERCENT ETHNICITY TOTAL,79.9,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
29,30,COUNT PERMANENT RESIDENT ALIEN,0.5,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
30,31,PERCENT PERMANENT RESIDENT ALIEN,0.061,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
31,32,COUNT US CITIZEN,8.9,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
32,33,PERCENT US CITIZEN,0.739,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
33,34,COUNT OTHER CITIZEN STATUS,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
34,35,PERCENT OTHER CITIZEN STATUS,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
35,36,COUNT CITIZEN STATUS UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
36,37,PERCENT CITIZEN STATUS UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
37,38,COUNT CITIZEN STATUS TOTAL,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
38,39,PERCENT CITIZEN STATUS TOTAL,80,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
39,40,COUNT RECEIVES PUBLIC ASSISTANCE,2.3,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
40,41,PERCENT RECEIVES PUBLIC ASSISTANCE,0.151,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
41,42,COUNT NRECEIVES PUBLIC ASSISTANCE,7.1,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
42,43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
43,44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
44,45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
45,46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,0,0,0,0,0,0,0,...,0,100,0,0,0,1,0,0,0,100
46,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
47,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
48,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
49,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
50,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

## Level Up (Optional) - Loading Corrupt CSV files

Occasionally, you encounter some really ill-formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is supposed to use quotes to differentiate between the commas denoting fields and the commas within those fields themselves. For example, we could have a table like this:  

`ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restaurant was pretty good, we had a great time.,98765`

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
`"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restaurant was pretty good, we had a great time.","98765"`

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled `'Yelp_Reviews_Corrupt.csv'`. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [11]:
# Hint: Here's a useful programming pattern to use
try:
    # Do something
except Exception as e:
    # Handle your exception e

IndentationError: expected an indented block after 'try' statement on line 2 (2533573781.py, line 4)

## Summary

Congratulations, you now practiced your Pandas-importing skills.